osx_image: xcode11.3
language: objective-c

branches: 
  only: 
    - feature/test
notifications:
    email: false
    install: 
      - gem install bundler
      - bundle install 
script: 
  - bundle exec fastlane feature
