osx_image: xcode11.3
language: objective-c

before_install:
  - pod install

branches: 
  only: 
    - master
    - develop
    - feature/test
notifications:
    email: false

    install: 
      - gem install bundler
      - bundle install 
      - gem install rest-client

    slack: 
      room: 
        - wemouv:a2ITH4WqUauqjPjZKQ6UOJCL#travis
      on_success: always  # change: send a notification when the build status changes.
      on_failure: always  # always: always send a notification.
      template:
        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
        - "Execution time: *%{duration}*"
        - "Message: %{message}"

script: 
  - bundle exec fastlane ios email
  - bundle exec fastlane ios feature
  - bundle exec fastlane ios release
