# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :feature do
    increment_build_number(
      xcodeproj: "./path/WeMoov/WeMoov.xcodeproj"
    )
  end
  desc "Description of what the lane does"
  lane :release do
    run_tests(
      xctestrun: "/path/WeMoovTests.xctestrun"
    )
    build_app(scheme: "WeMoov",
              workspace: "WeMoov.xcodeproj",
              include_bitcode: true
    )
    scan(
      workspace: "Example.xcworkspace",
      devices: ["iPhone 6s", "iPhone 7", "iPhone 8","iPhone X", "iPhone 11", "iPhone 11 pro max"]
    )
    upload_to_app_store
    slack
    notification(subtitle: "Finished Building", message: "Ready to upload...")
  end
end
