# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :feature do
    increment_build_number
  end
  desc "Description of what the lane does"
  lane :release do
    # build_app(scheme: "WeMoov")
    # upload_to_testflight
    # notification(subtitle: "Finished Building", message: "Ready to upload...")
    get_certificates(
      username: "esgi.dev.moc@gmail.com"
    ) 
    sigh
    gym
    pilot(distribute_external:false)
  end
  desc "Send email"
  lane :email do 
    mailgun(
      apikey: "7f67565216168b32d06d43db830b47dd-52b6835e-3152b92b",
      to: "taj.singh0715@gmail.com",
      from: "wemouv@gmail.com",
      success: true,
      message: "Bonjour, une nouvelle version de WeMoov sera bientot disponible. Merci de nous faire confiance, l'équipe WeMoov.",
    )
  end
end
