# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :feature do
    increment_build_number
  end
  desc "Description of what the lane does"
  lane :release do
    # build_app(scheme: "WeMoov")
    # upload_to_testflight
    # notification(subtitle: "Finished Building", message: "Ready to upload...")
    cert
    sigh
    gym
    pilot(distribute_external:false)
  end
end
